### ISSUE TITLE
Les 5 example useCreateNote

### ISSUE THREAD

**Issue by JMesens-TM** [it-graduaten/Releases-JavaScript-Leerlijn#1]
<img width="993" alt="afbeelding" src="https://github.com/it-graduaten/Releases-JavaScript-Leerlijn/assets/118686834/a0eed730-302f-48f0-a4ca-68e9eea82996">

The useCreateNote will optimistically delete a note instead of add L12. (correct in solution, wrong in the text)

**Comment by SebastiaanHenau** [comment]
Fixed in 4b22a37e1ebf460a549ad688a402c79881fe0840.
